"use client"
import { Inter } from "next/font/google";
import "./globals.css";
import CustomNavbar from "@/components/Navbar/CustomNavbar";
import Footer from "@/components/Footer/Footer";
import { ToastContainer } from "react-toastify";
import UserProvider from "@/helper/userProvider";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserProvider>
          <ToastContainer />
          <CustomNavbar />
          {children}
          <Footer />
        </UserProvider>
      </body>
    </html>
  );
}
